// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADPj6Uvcso-w9tMdtUlQhqtKUw66Z39Yo',
    appId: '1:918521485667:web:af9e17a63ffd2e3b3e1b56',
    messagingSenderId: '918521485667',
    projectId: 'fatconnect-79149',
    authDomain: 'fatconnect-79149.firebaseapp.com',
    storageBucket: 'fatconnect-79149.firebasestorage.app',
    measurementId: 'G-176TQMJSWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkvMbpkpZgouf4LT7mO55hBLOaiO_3_zg',
    appId: '1:918521485667:android:aec195e943d3ae313e1b56',
    messagingSenderId: '918521485667',
    projectId: 'fatconnect-79149',
    storageBucket: 'fatconnect-79149.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu9oqijn0NeuE5FfheKnbed9Z-u34yTk0',
    appId: '1:918521485667:ios:013e8a688c5a845f3e1b56',
    messagingSenderId: '918521485667',
    projectId: 'fatconnect-79149',
    storageBucket: 'fatconnect-79149.firebasestorage.app',
    iosBundleId: 'com.example.fatconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu9oqijn0NeuE5FfheKnbed9Z-u34yTk0',
    appId: '1:918521485667:ios:013e8a688c5a845f3e1b56',
    messagingSenderId: '918521485667',
    projectId: 'fatconnect-79149',
    storageBucket: 'fatconnect-79149.firebasestorage.app',
    iosBundleId: 'com.example.fatconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADPj6Uvcso-w9tMdtUlQhqtKUw66Z39Yo',
    appId: '1:918521485667:web:b3afb2b86534442d3e1b56',
    messagingSenderId: '918521485667',
    projectId: 'fatconnect-79149',
    authDomain: 'fatconnect-79149.firebaseapp.com',
    storageBucket: 'fatconnect-79149.firebasestorage.app',
    measurementId: 'G-MZBMP7ZY02',
  );
}
